; PlatformIO Project Configuration File for ESP32-WROOM-32U
; External Display Scale Indicator + Web Portal + LittleFS

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
